### ISSUE TITLE
Video Continues Playing Upon Close

### ISSUE THREAD

**Issue by james0r** [haiafara/vue-it-bigger#318] opened 2022-04-22 00:43 UTC
Maybe this is by design, but after closing the overlay, youtube videos continue playing.

Anyone have a method of stopping the video on overlay close? 

thanks!

**Comment by janosrusiczki** [comment] 2022-11-15 07:18
Thanks for reporting, this is actually a duplicate of #125.

**Closed by janosrusiczki** 2022-11-15 07:18 UTC
